
// -----------------------------------------------------------
//  This program is auto generated by tora compiler. Please
//  do not edit this file.
// -----------------------------------------------------------
package main

import (
	"tora/component"
	"tora/example/plugin"
	"tora/example/greeter"
	
)

var (
	comps    = &component.Components{}
	services = &component.Services{}
)

func Setup() {
	// Registrations of components
	comps.Register(&plugin.Plugin{})
	comps.Register(&greeter.Greeter{})
	
	// Setup services
	services.Setup(comps)
}

func List() {
	services.List()
}

func Handle(cmd string, data []byte) error {
	return services.Handle(cmd, data)
}
	